name: Documenter
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
      # - name: Install dependencies
      #   run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: >
          cd docs;
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
          julia --color=yes makedocs.jl
